### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by srohde** [googlearchive/todomvc#11]
The index.html is including

```
<script src="../polymer/polymer.js"></script>
```

This is not mentioned in the Readme. Also when polymer is checked out into the same parent running the local webserver causes a 404 on the polymer.js.

When I run the index.html in Canary with `--allow-file-access-from-files --disable-web-security` I get a little further but get these errors:

polymer.min.js:3: GET file:///Users/srohde/Documents/polymer-all/projects/todomvc/todomvc/components/director/build/director.min.js  

Uncaught ReferenceError: Router is not defined

**Comment by morethanreal** [comment]
Have you run "bower install" after checking out the repo? TodoMVC requires third party libraries such as director to be fetched from bower.

I fixed index.html to use `polymer.min.js` from bower. That said, it still won't work because this repo is updated with the latest changes to polymer, and the bower repo is not up to date. This should be fixed with the next push to the polymer stable branch. Perhaps we also need master/stable branches for todomvc?

**Comment by srohde** [comment]
Thanks!
Yes, I ran bower install/update.
With the fixed index.html I now get this error below. When will be the next push the polymer stable branch?

Uncaught TypeError: Property 'Polymer' of object [object Object] is not a function inline[1244]:2
(anonymous function) inline[1244]:2
g.parseScript boot.js:17
(anonymous function) boot.js:17
g.parse boot.js:17
g.parseLink boot.js:17
(anonymous function) boot.js:17
g.parse boot.js:17
g.parseLink boot.js:17
(anonymous function) boot.js:17
g.parse boot.js:17
g.parseLink boot.js:17
(anonymous function) boot.js:17
g.parse boot.js:17
(anonymous function) boot.js:17
l.checkDone boot.js:17
l.tail boot.js:17
(anonymous function) boot.js:17
l.receive boot.js:17
(anonymous function) boot.js:17
(anonymous function) boot.js:17

**Comment by morethanreal** [comment]
I think it's scheduled for two weeks from now. In the meantime, commit 2a75c68376b8da0f93b49d9791b13fd945d483cd should work.

**Comment by togakangaroo** [comment]
The issue for me seemed to be that `bower update` installed everything into the bower_components directory while the application is looking for `components`. Renaming one for the other fixed the issue.

**Comment by dfreedm** [comment]
@togakangaroo that should now be fixed in af4ff23a55589ebd2f5f56003b790b00d0f6eecc

**Comment by dfreedm** [comment]
@srohde @togakangaroo This should all be working now. Please reopen if you still have issues.

**Comment by addyosmani** [comment]
btw, if you find this to be a pain-point it might be useful to check-in your bower components: http://addyosmani.com/blog/checking-in-front-end-dependencies/

This does require updating them when Polymer pushes a new release however.
