### ISSUE TITLE
Model status

### ISSUE THREAD

**Issue by addyosmani** [googlearchive/todomvc#4]
I had a chat with @sjmiles about a few of the different model variations for Polymer apps that can currently be found over in https://github.com/Polymer/projects/tree/stable/todomvc. 

I see that in this version of the app, the model layer has been implemented as a component. Should it be assumed that this is going to be the way Polymer advocates the model layer being implemented? :)

I ask as I've been in the process of starting to get Polymer into the TodoMVC repo (well, all of the variations) so that we could get back some feedback on which model variant developers like. Just wondering if this is the one you settled on :)

If so, I'm happy to nuke that branch over on TodoMVC and bring this one into our labs folder.

**Comment by ebidel** [comment]
@addyosmani Chatted with the team yesterday. I was also concerned about having 3-4 different versions of todomvc without a recommended way. We've decided to go froward with this version as Polymer's canonical example. This particular one really drives home the point that everything in Polymer can/should be an element where possible.

The other examples were experiments by members of the team. They're not technically wrong and will likely go away soon. I'm writing a TodoMVC walkthrough that could cover these other approaches.

**Comment by addyosmani** [comment]
That sounds fantastic, @ebidel. I'm really glad to hear I wasn't the only one with concerns about so many variations and it's exciting to hear you have a walkthrough planned. I'll move ahead with getting this version into our labs and will ping you and Scott about additional details we might want to include on the site about it.

One suggestion: it may be worth moving the other model variations into a branch or repo which isn't going to be publicised. They could serve as reference points in the future should someone be on the lookout for an alternative way to handle the model layer.

**Comment by ebidel** [comment]
+1 on holding onto those other todomvc examples somewhere. @sorvell @morethanreal can we put them in a "non visible" branch instead of nuking them?

**Comment by morethanreal** [comment]
Sure, I'll do that.

**Comment by morethanreal** [comment]
branches added.
