### ISSUE TITLE
Small editing bug

### ISSUE THREAD

**Issue by addyosmani** [googlearchive/todomvc#6]
After a `bower install` to fetch components, I fired up a server to test the app and ran into a small visual bug with adding new items. 

Enter in text and the editing field, which should be visible on double-click, is instead persistently visible. Hiding the text input field by default should fix this.

Chrome:

![screen shot 2013-06-14 at 18 59 16](https://f.cloud.github.com/assets/110953/655797/2db099da-d51c-11e2-85d8-49c9bed3096a.png)

Safari:

![screen shot 2013-06-14 at 18 58 59](https://f.cloud.github.com/assets/110953/655799/351cc5ea-d51c-11e2-8db2-0206bd191c5f.png)

**Comment by morethanreal** [comment]
This is because the stable polymer branch fetched by bower is old. It should be better once we push a new stable later today.

**Comment by addyosmani** [comment]
Fantastic. Thanks @morethanreal! :)
