### ISSUE TITLE
App not functional in latest Chrome stable

### ISSUE THREAD

**Issue by Daniel-Hug** [googlearchive/todomvc#9]
Using Chrome v27.0.1453.116 m [Polymer TodoMVC](http://todomvc.com/labs/architecture-examples/polymer/index.html) looks like this:
![It appears to be broken! :(](http://imgh.us/Polymer_TodoMVC.png)

In the console:

> Uncaught TypeError: Object `function Array() { [native code] }` has no method 'observe' in boot.js on line 17.

**Comment by dfreedm** [comment]
Do you have "Experimental WebKit Features" or "Experimental Javascript Features" turned on? If so, turn them off and try again.

@rafaelw this look like Object.observe feature detection gone awry?

**Comment by ebidel** [comment]
This has already tripped a few people up. Definitely some up with the
feature detection.

**Comment by Daniel-Hug** [comment]
@azakus Disabled 'em both and it worked.

**Comment by rafaelw** [comment]
Yeah. The full Object.observe implementation hasn't made it to Release. Only Canary & Dev so far. I thought I had proper feature detection for the full implementation. I'll go test against Beta & Release.

**Comment by sorvell** [comment]
@rafaelw 

https://github.com/rafaelw/ChangeSummary/blob/master/change_summary.js#L19

Should that be || and not && ?

**Comment by rafaelw** [comment]
Yup. Good catch: https://github.com/rafaelw/ChangeSummary/commit/d71c0234049b81b18493b089dd91c3a12a2f00f0
